Develop
pikachuha111/Diploma pull request #8
Opened 2023-03-06 08:32 UTC by pikachuha111

Project is not ready yet :)

2023-03-07 09:01 UTC, wildpioneer requested changes

2023-03-07 09:01 UTC, wildpioneer commented on src/main/java/configuration/ReadPropertiesUI.java
> +public class ReadPropertiesUI {
Два одинаковых класса для чтения настроек - забыли один удалить?

2023-03-07 09:01 UTC, wildpioneer commented on src/test/java/adapters/BookAdapter.java
> +        String bookIdentifier = null;
А с какой целью данная переменная устанавливается в NULL?

2023-03-07 09:01 UTC, wildpioneer commented on src/test/java/adapters/BookAdapter.java
> +        for (Book bookObject : collectionBooks.getBooks()) {
На будущее, вместо этой конструкции for существует технология stream() - почитайте
https://www.baeldung.com/java-stream-filter-lambda

2023-03-07 09:01 UTC, wildpioneer commented on src/test/java/models/HumanUI.java
> +    private String firstName;
Форматирование должно быть единообразный - а тут класс HumanUI отличается от User

2023-03-07 09:01 UTC, wildpioneer commented on src/test/java/pages/CheckBoxPage.java
> +    private String checkBoxPageUrl = "https://demoqa.com/checkbox";
Прямая ссылка с указанием сервера???

2023-03-07 11:38 UTC, pikachuha111 commented on src/main/java/configuration/ReadPropertiesUI.java
> +public class ReadPropertiesUI {
Да, при реафакторинге 2ой класс удален

2023-03-07 11:39 UTC, pikachuha111 commented on src/test/java/adapters/BookAdapter.java
> +        String bookIdentifier = null;
Поскольку данная переменная может быть не проинициализирована через цикл for each

2023-03-08 19:26 UTC, xGroZn commented on src/test/java/pages/CheckBoxPage.java
> +    private String checkBoxPageUrl = "https://demoqa.com/checkbox";
исправил

2023-03-08 19:27 UTC, xGroZn commented on src/test/java/models/HumanUI.java
> +    private String firstName;
класс HumanUI создан для создания сущности на другом сайте

2023-03-13 18:54 UTC, wildpioneer approved these changes

2023-03-13 18:54 UTC, wildpioneer commented on src/test/java/tests/gui/NegativeUiTests.java
> +        $(By.id("name"))
Поиск элемента в тесте????

2023-03-13 18:54 UTC, merged